title: Mohsen Karimi # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a CFD engineer with a passion for understanding how numerical modeling and simulations can solve 
  real world problems more efficiently. In this portfolio page I publish examples of my works.
  <br><br>
  <a href="https://www.linkedin.com/in/mohsenka/">LinkedIn</a> 
  <br><br>
  <a href="https://gitlab.com/mohsenk_/">GitLab</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
