title: Mohsen Karimi # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CFD enthusiast with passion for coding.
  <br><br>
  <a href="https://www.linkedin.com/in/mohsenka/">LinkedIn</a> 
  <br><br>
  <a href="https://gitlab.com/mohsenk_/">GitLab</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
